### ISSUE TITLE
Build swift-nio-ssl in Xcode 15 produces warnings

### ISSUE THREAD

**Issue by mylaluna** [apple/swift-nio-ssl#438] opened 2023-07-17 07:51 UTC
I am testing my App in iOS 17 with Xcode 15 beta 4.
I found myself receiving 200+ warnings for just building the app.

Under the Build target CNIOBoringSSL in Package swift-nio-ssl, I received warning as following:
<img width="623" alt="image" src="https://github.com/apple/swift-nio-ssl/assets/2162747/d417e8d0-4e13-408b-9736-96141e29b135">

Is this the right place to report this kind of problem?

- Apple Swift version 5.9 (swiftlang-5.9.0.120.7 clang-1500.0.34.3)
- Target: arm64-apple-darwin23.0.0

- Darwin Macbook-Pro 23.0.0 Darwin Kernel Version 23.0.0: Fri Jun 30 17:50:12 PDT 2023; root:xnu-10002.0.168.505.3~1/RELEASE_ARM64_T6000 arm64

**Comment by dnadoba** [comment] 2023-07-17 09:03
Sadly we can't do much about it because they come from BoringSSL and not this project.
Duplicate of https://github.com/apple/swift-nio-ssl/issues/418

**Closed by dnadoba** 2023-07-17 09:03 UTC

**Comment by mylaluna** [comment] 2023-07-18 01:06
Will you report this to BoringSSL project?

**Comment by mylaluna** [comment] 2023-07-24 04:16
Thanks for the follow up. @Lukasa
